[build]
  command = "npm run build"
  publish = "_site"

[[redirects]]
  from = '/donuts/*'
  to = '/.netlify/functions/donuts/:splat'
  status = 200

[[redirects]]
  from = '/types'
  to = '/.netlify/functions/donuts'
  status = 200
  targetPort = 8080
